name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
          
      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install yarn
        run: npm i -g yarn

      - name: Install deps
        run: pnpm i


      - name: Intall npm-demo deps
        run: cd ./fixtures/npm-demo && npm install

      - name: Intall pnpm-demo deps
        run: cd ./fixtures/pnpm-demo && pnpm install

      - name: Intall yarn-demo deps
        run: cd ./fixtures/yarn-demo && yarn install

      - name: Intall yarn-workspace-demo deps
        run: cd ./fixtures/yarn-workspace-demo && yarn install

      - name: Intall yarn2-demo deps
        run: cd ./fixtures/yarn2-demo && yarn set version berry && yarn install

      - name: Build and Test
        run: pnpm run test

      - name: Release
        run: pnpx semantic-release --branches main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}